services:

  api:

    build: .

    container_name: order-platform-api

    command: >
      uvicorn app.api.main:app
      --host 0.0.0.0
      --port 8000

    ports:
      - "8000:8000"

    depends_on:

      rabbitmq:

        condition: service_healthy

    environment:

      RABBITMQ_HOST: rabbitmq

    volumes:
      - .:/app

    restart: unless-stopped


  dispatcher:

    build: .

    container_name: order-platform-dispatcher

    command: python -u -m app.main

    depends_on:

      rabbitmq:

        condition: service_healthy

    environment:

      RABBITMQ_HOST: rabbitmq

    volumes:
      - .:/app

    restart: unless-stopped


  consumer:

    build: .

    container_name: order-platform-consumer

    command: python -u -m app.main_consumer

    depends_on:

      rabbitmq:

        condition: service_healthy

    environment:

      RABBITMQ_HOST: rabbitmq

    volumes:
      - .:/app

    restart: unless-stopped


  rabbitmq:

    image: rabbitmq:3-management

    container_name: order-platform-rabbitmq

    ports:
      - "5672:5672"
      - "15672:15672"

    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 10

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

    restart: unless-stopped


  prometheus:

    image: prom/prometheus

    container_name: order-platform-prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

    restart: unless-stopped


  grafana:

    image: grafana/grafana

    container_name: order-platform-grafana

    ports:
      - "3000:3000"

    volumes:
      - grafana_data:/var/lib/grafana

    restart: unless-stopped


volumes:

  rabbitmq_data:

  grafana_data: