from enum import Enum


class OrderStatus(str, Enum):
    PENDING = "PENDING"

    INVENTORY_RESERVED = "INVENTORY_RESERVED"

    PAYMENT_AUTHORIZED = "PAYMENT_AUTHORIZED"

    CONFIRMED = "CONFIRMED"

    FULFILLMENT_REQUESTED = "FULFILLMENT_REQUESTED"

    FULFILLED = "FULFILLED"

    CANCELLED = "CANCELLED"

    REJECTED = "REJECTED"